=head1 NAME

ping_get_error - Return the last error message

=head1 SYNOPSIS

  #include <oping.h>

  const char *ping_get_error (pingobj_t *obj);

=head1 DESCRIPTION

The B<ping_get_error> method returns an error message indicating the last error
encountered. B<This method is not thread safe whatsoever.>

=head1 RETURN VALUE

A C<const> string representing the last error or an empty string if no error
was encountered yet.

=head1 SEE ALSO

L<liboping(3)>

=head1 AUTHOR

liboping is written by Florian "octo" Forster E<lt>ff at octo.itE<gt>.
Its homepage can be found at L<http://noping.cc/>.

Copyright (c) 2006-2017 by Florian "octo" Forster.
